name: Deploy Wasmer Axum Starter to Wasmer Edge

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Build and Deploy Wasmer Axum Starter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies (ld, build tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential binutils

      - name: Verify ld installation
        run: ld --version

      - name: Configure Cargo git fetch
        run: |
          mkdir -p ~/.cargo
          echo '[net]' > ~/.cargo/config.toml
          echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml

      - uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install cargo-wasix
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-wasix

      - name: Check for cargo-wasix updates (optional)
        run: cargo wasix self update-check

      - name: Setup Wasmer CLI
        uses: wasmerio/setup-wasmer@v2

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Update Cargo dependencies fully
        run: cargo update

      - name: Type check with Wasix target
        run: cargo wasix check --target wasm32-wasmer-wasi --verbose --release --locked

      - name: Build Wasix binary
        run: cargo wasix build --target wasm32-wasmer-wasi --verbose --release --locked

      - name: Deploy to Wasmer Edge
        run: wasmer deploy --token=${{ secrets.WASMER_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
