name: Rust WASIX Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install cargo-wasix
        run: cargo install cargo-wasix

      - name: Run cargo wasix check
        run: cargo wasix check --target wasm32-wasmer-wasi --release --locked --verbose
